spring.application.name=shopsample
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.root=INFO
logging.level.com.springapi.shopsample=DEBUG

# Error details - enabled by default for development
app.show-error-details=true